#!/bin/bash
grep -q '^vm\.nr_hugepages=.*' /etc/sysctl.conf || echo 'vm.nr_hugepages=128'>>/etc/sysctl.conf
sudo sysctl -p
docker run --read-only -d --name xmrig --rm --device=/dev/hugepages:/dev/hugepages abrakadabra21099/alpine-xmrig -O $HOSTNAME:x --rig-id=$HOSTNAME -o rig5.rigss.ru:7773 -o rig4.rigss.ru:7773 -o rig3.rigss.ru:7773 -o rig2.rigss.ru:7773 -o rig1.rigss.ru:7773 && \
docker logs -f xmrig
